# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sudoku' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sudoku
  pod 'SnapKit'
  pod 'RxRealm'

  pod 'Swinject'

  pod 'lottie-ios'
  
  target 'SudokuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SudokuUITests' do
    # Pods for testing
  end

end
